### ISSUE TITLE
cdata serialize with __eq metamethod

### ISSUE THREAD

**Issue by sonoro1234** [gvx/bitser#25] opened 2021-03-25 14:54 UTC
Hi,

When doing bitser.dumps for a cdata (of type vec2) with `__eq` methamethod (via metatype) which expects two vec2 to compare I get an error in https://github.com/gvx/bitser/blob/master/bitser.lua#L231 because ffi.typeof(vec2) is not a vec2.

The purpose of  https://github.com/gvx/bitser/blob/master/bitser.lua#L231 is to differentiate cdata from ctype and could be perhaps done other way: tostring(cdata_or_ctype):match"^ctype"

**Comment by gvx** [comment] 2021-03-25 18:30
Could you provide a minimal code sample that reproduces the problem? That way I can test any potential solution.

I don't  think the `tostring` approach will work, [given the LuaJIT documentation](https://luajit.org/ext_ffi_api.html#tostring):

>     s = tostring(cdata)

> Returns a string representation of the value of 64 bit integers (`"nnnLL"` or `"nnnULL"`) or complex numbers (`"re±imi"`). Otherwise returns a string representation of the C type of a ctype object (`"ctype<type>"`) or a cdata object (`"cdata<type>: address"`), unless you override it with a `__tostring` metamethod (see `ffi.metatype()`).

**Comment by sonoro1234** [comment] 2021-03-25 21:04
It is tostring(ctype) case.
I will provide test case tomorrow.

**Comment by sonoro1234** [comment] 2021-03-26 07:47
```Lua
local ffi = require"ffi"
local bitser = require"bitser"

ffi.cdef [[
typedef struct vec2 { double x, y;       } vec2;
]]

local metav2 = {
    __eq = function(a,b) return a.x == b.x and a.y == b.y end,
    __tostring = function(v) return '<'..v.x..','..v.y..'>' end
}
metav2.__index = metav2
local vec2 = ffi.metatype('vec2',metav2)

local a = vec2(1,2)
local b = bitser.loads(bitser.dumps(a))

print(a,b)
```
It does error.
Changing `if ty == value then` for `if tostring(value):match"^ctype" then` succeds

**Comment by gvx** [comment] 2021-03-31 06:32
My issue with your proposed solution is that it will fail on ctypes with metatables like `{__tostring = function(v) return 'ctype object' end}`.

What seems to work fine is

```lua
local success, eq = pcall(function() return value == ty end)
if success and eq then
```

I'll add more test cases to the spec, but it seems to work, and the performance impact seems to be minimal.

**Comment by sonoro1234** [comment] 2021-03-31 16:32
Yes, it works with provided example.

**Comment by sonoro1234** [comment] 2024-12-16 17:55
Is this going to be added?

**Comment by gvx** [comment] 2024-12-29 17:02
Currently bitser does not support cdata, so I'm marking this as a wontfix.

**Closed by gvx** 2024-12-29 17:02 UTC
Labels: wontfix, cdata
